### ISSUE TITLE
mrkzero does not work 

### ISSUE THREAD

**Issue by Fesoj3** [adafruit/Adafruit_NeoPixel_ZeroDMA#11]
i used the this lib #include <Adafruit_NeoPixel.h> and used the simple example i managed to get an green led on pin 6.

when i switch to this lib#include <Adafruit_NeoPixel_ZeroDMA.h>
i start the strand example. on pin 5 -    Serial.println(strip.begin())gives me 1.
but icant see a light

**Comment by ladyada** [comment]
not every pin works- it must be one with SPI MOSI capabilities - and feather m0 has different pins than mkr zero!

**Comment by Fesoj3** [comment]
if  i am write you suggest
// On Feather M0, Arduino Zero, etc.: 5, 11, A5 and 23 (SPI MOSI).
Pin 23.
I tested it on 23 doesnt work 
on the board its writen 8 on the silksckreen next to the mosi pin doesnt work too.


so what am i doing wrong?

**Comment by Fesoj3** [comment]
> not every pin works- it must be one with SPI MOSI capabilities - and feather m0 has different pins than mkr zero!

if i am right you suggest
// On Feather M0, Arduino Zero, etc.: 5, 11, A5 and 23 (SPI MOSI).
Pin 23.
I tested it on 23 doesnt work
on the board its writen 8 on the silksckreen next to the mosi pin doesnt work too.

so what am i doing wrong?
