### ISSUE TITLE
Compatibility is broken since last release 1.1.1

### ISSUE THREAD

**Issue by Adminius** [adafruit/Adafruit_NeoPixel_ZeroDMA#12]
Hi @ladyada 
a made a PR #5 with a flexible begin function to define own pins.
Since this #10 this function is private :/

Why did you made it?

**Comment by ladyada** [comment]
hmm dont remember, you just need it protected not private right?

**Comment by Adminius** [comment]
I need it for this:
https://github.com/KONNEKTING/ALEDD1/blob/master/led_functions.h#L45
-> not private

**Comment by ladyada** [comment]
try the latest commit - we will release if it works!

**Comment by ladyada** [comment]
(reopen if not solved)

**Comment by Adminius** [comment]
Hi @ladyada , 
Sorry, I had no time until today to test it....
and it doesn't work :/

> 'boolean Adafruit_NeoPixel_ZeroDMA::_begin(SERCOM*, Sercom*, uint8_t, uint8_t, uint8_t, uint8_t, SercomSpiTXPad, SercomRXPad, EPioType)' is protected within this context

Do I need it completely public or is there a trick to use it as protected? (my example is linked above).
If public, may be you can revert it to "pre 1.1.1" state with *begin* instead of *_begin*?

**Comment by ladyada** [comment]
why are you re-initializing the sercom? thats not recommended/supported

**Comment by Adminius** [comment]
Normal init function is here:
https://github.com/KONNEKTING/ALEDD1/blob/master/led_functions.h#L83

this one is only for testing:
https://github.com/KONNEKTING/ALEDD1/blob/master/led_functions.h#L45

after that MCU will be completely rebooted:
https://github.com/KONNEKTING/ALEDD1/blob/master/button.h#L15-L28

It's user friendly way to find out wich type of GRB/RGB... combination this strip is:
https://github.com/KONNEKTING/ALEDD1/blob/master/led_functions.h#L34-L40

also, it's a a way to find out how much LEDs on this strip are connected:
https://github.com/KONNEKTING/ALEDD1/blob/master/led_functions.h#L50-L54

**Comment by Adminius** [comment]
Hi @ladyada 
any news/decision?

**Comment by ladyada** [comment]
hi please submit a PR for what you need to fix and test it. :)
