### ISSUE TITLE
Arduino Nano 33 IOT question

### ISSUE THREAD

**Issue by jarnoburger** [adafruit/Adafruit_NeoPixel_ZeroDMA#19]
So this uses DMA , using SPI , right ?
So can i use my WifiNina library next to it without weird conflicts ? (because i think it talks over SPI also)

**And i am trying to find my pinout.**
I have this data now : 
-The SAMD21 MCU has 6 SERCOM based SPIs. SERCOM1 is available on pins 1, 14, and 15.
-Metro M0 or Arduino Zero: pins 5, 12 and MOSI*.
-the new Nanos have pin mapping similar to classic Nano. so SPI is on pins 10,11,12,13
 PIN         MKR PIN     PIN        DESCRIPTION 
 | 22         | 1                |  PA12  | NINA_MOSI    
 | 23         | 2                |  PA13  | NINA_MISO     
 | 24         | 4                |  PA14  | NINA_CS      
 | 25         | 3                |  PA15  | NINA_SCK      
 Which one , would be my pin , that i use ??

**Comment by PaintYourDragon** [comment]
Going through some old feedback, sorry for the delay. If this is still relevant to your needs, the library’s been updated for NANO 33 IoT support, and works on pins 4, 6, 7, A2, A3, or MOSI on that board (if using MOSI, the SPI peripheral can’t be used for other tasks). SERCOM0 is the only one that doesn’t conflict with other peripherals on the NANO 33.
