### ISSUE TITLE
Library License

### ISSUE THREAD

**Issue by Prodigalson0** [adafruit/Adafruit_NeoPixel_ZeroDMA#2]
I looked through the available source, but I couldn't find a license.

Have I missed something obvious?

**Comment by ladyada** [comment]
@PaintYourDragon hey wanna add a license? MIT or BSD, whatever you like

**Comment by per1234** [comment]
Fixed by https://github.com/adafruit/Adafruit_NeoPixel_ZeroDMA/commit/b07d3b558f6e91d57c35e7ce5c9506495b4f8a05

**Comment by ladyada** [comment]
w00t thx
