### ISSUE TITLE
multiple DMA objects does not work

### ISSUE THREAD

**Issue by silvan2468** [adafruit/Adafruit_NeoPixel_ZeroDMA#22]
Hy

I am using an Arduino Nano 33 IoT with Adafruit neopixel side leds together with an RGBW neopixel stripe and some servos.
The servos trembled when using the "ordinary" neopixel library. Fortunately I found your solution with ZeroDMA. Unfortunately, it does not work with two objects of stripes. Even the pin asignement goes wrong.
I use pins 4 and 7.
If I only use one object, everything goes right for both pins. Only in combination with two objects it does not work.

The NeoPxl8 library I cannot use because I have two different types of neopixels. 

Mixing one DMA object with objects from the "ordinary" neopixel library works. But makes no sense. Servo will tremble again.

I really like Adafruit products and bought already a lot of them. I kindly hope Adafruit/someone will find a solution, soon. Also because you wrote, that it theoreticaly should work.
I am also willing to test your solution as soon you have. 

If you are doing some work here: My modifyable code plans to update the numbers of pixels, RGB type, etc. AFTER the initialisation of the objects. So the up to now missing update-functions would also be very helpful for me if someone implement them.

Thanks a lot and kind regards
Silvan

**Comment by PaintYourDragon** [comment]
Not actually a DMA problem, but a shortage of SERCOMs, which can’t be shared — most of the library-compatible pins on this particular board all go to SERCOM0, so it’s any ONE of those pins at a time. The exception is MOSI (D11) on SERCOM1…unless you need SPI for something else. Tested on nano 33 IoT on pins 4 and 11, can use both concurrently, just remember to call begin() for both. If you can’t lose SPI, would suggest then running it as one long strip, routing DO from the end of one back to DI on the next.

No plans to add the update functions. Those were a mistake in the original lib and are only kept for back-compatibility. Well-behaved code using runtime-configured pixels should instead use the “new” operator, like so:
```
Adafruit_NeoPixel_ZeroDMA *strip; // global
...
strip = new Adafruit_NeoPixel_ZeroDMA(NUM_PIXELS, PIN, NEO_GRB); // initted later
strip->begin(); // use -> instead of . for begin(), show(), everything
```

**Comment by silvan2468** [comment]
Hey paintyourdragon
Thanks a lot for your answer and the hint with "new".

That would be bad for me, because i need the spi for a display, an imu and an sd card. All together. So no chance to loose the MOSI pin.
Further I have two different types of neopixels (side leds 4020 from adafruit and in minimum one looong stripe (better would be two stripes) with rgbW neopixels. And as I wrote time and interrupt critical interrupts from a balancing control loop and up to 12 servos and also up to 12 signals to read with interrupts from a remote control receiver.

Do you perhaps know another solution/library to drive at least two different types of neopixels WITHOUT problems with interrupts? Otherwise i would have to cancel the side leds because they are less important for the function of my project. But they look sooo nice :)

Thanks a lot for your help
Silvan

PS: I can confirm that I am also able to drive the side neopixel at the same time as with the MOSI pin.

**Comment by silvan2468** [comment]
Another idea:
I can't give up SPI. But i can give up rs232 which uses sercom5 according to variant.cpp.
Is this possible? If yes, can you please add pin 1 (TX) to the possible pins on arduino nano 33 iot?

Thanks
